### ISSUE TITLE
Ep1: Different file formats

### ISSUE THREAD

**Issue by gcapes** [mawds/r-programming-intro#16]
How should learners inspect the file formats? Obviously by opening with a text editor  - I would go to notepad++, but you can also open with R studio. I don't know whether it's worth giving a nudge in the right direction, or whether the idea is to set the tone that they'll have to think a bit more in this course?

**Comment by mawds** [comment]
I assume Notepad++ is installed in G11?  If so, this is fixed in commit c166e4d8abf01bf26a626a46290a1cb273b625c2

**Comment by gcapes** [comment]
It is currently and should be next year too.
