### ISSUE TITLE
Ep1: Fixed width explanation

### ISSUE THREAD

**Issue by gcapes** [mawds/r-programming-intro#18]
Very minor point, but fixed width isn't a very common format (only Fortran?) so might be new to lots of people.
> We can make use of the fact that each variable starts in the same column in each row;

I didn't immediately twig that here, a column refers to a single character rather than a new item of data. I might reword along the lines of 
> We can see that this data is 'fixed width' i.e. columns are not separated by a character like a comma, but data is padded with spaces so that the columns are always the same number of characters wide.

**Comment by mawds** [comment]
That's much clearer - thanks.  Fixed in commit c838ffd8ba7dc406b8c0a3095c3badbd78d13947
