### ISSUE TITLE
Ep1: loading co2_weekly_mlo.txt

### ISSUE THREAD

**Issue by gcapes** [mawds/r-programming-intro#19]
Is it obvious how to generate the load specification? Running `read_table("data/co2_weekly_mlo.txt")` doesn't generate much in the way of correct guesses:

```
co2_weekly = read_table("data/co2_weekly_mlo.txt")
Parsed with column specification:
cols(
  `#` = col_character(),
  `--------------------------------------------------------------------` = col_character()
)
```

**Comment by mawds** [comment]
You're right - this covers too much too quickly.    I've spaced it out a bit in 2af3b6ec28a0b2ab8f4772bbead453325339c1d4  

Having to cut and paste a huge command in at the end doesn't seem ideal though - any ideas?

**Comment by gcapes** [comment]
Looks much better! I don't see any problem with how you've done it. The syntax should be familiar from the previous lesson, and the rationale for copy and pasting is sound.

**Comment by mawds** [comment]
OK.  Thanks.   I guess the length of the command can't be helped
Fixed in https://github.com/mawds/r-programming-intro/commit/2af3b6ec28a0b2ab8f4772bbead453325339c1d4
