### ISSUE TITLE
Ep1: ifelse typo in explanation

### ISSUE THREAD

**Issue by gcapes** [mawds/r-programming-intro#20]
>... If the element is FALSE the nth element of the **3rd** argument will be replaced. But the 3rd argument is only a single value…what’s going on here? 

It's the nth element of  the 2nd argument i.e. 'demodata' which is replaced using the 3rd argument.

**Comment by mawds** [comment]
I've introduced `ifelse()` far too quickly... have modified to break it down in more detail
